#
# Metrics services -- provides a web GUI to monitor Lighthouse nodes & docker host machine
#
version: "3.3"

services:
  eth2stats:
    container_name: eth2stats
    restart: unless-stopped
    image: alethio/eth2stats-client:latest
    command: eth2stats.node-name="SET-ME-TO-YOUR-NODE-NAME" --data.folder="/data" --eth2stats.addr="grpc.pyrmont.eth2.wtf:8080" --eth2stats.tls=false --beacon.type="v1" --beacon.addr="http://localhost:5052" --beacon.metrics-addr="http://localhost:5054/metrics"
    volumes:
      - eth2stats-data:/data
    network_mode: host
  prometheus:
    container_name: prometheus
    build:
      context: prometheus
    volumes:
      - prometheus-data:/prometheus
      - type: bind
        source: ./scrape-targets
        target: /prometheus/targets
    ports:
      - 9090:9090
    restart: unless-stopped
    network_mode: host
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    container_name: node_exporter
    restart: always
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.38.3
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    expose:
      - 8080
    network_mode: host
  grafana:
    container_name: grafana
    build:
      context: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    restart: unless-stopped
    network_mode: host

volumes:
    eth2stats-data:
    grafana-data:
    prometheus-data:
    targets:
